apiVersion: v1
kind: Service
metadata:
  name: zen-asr-server
  namespace: dev-omi-backend
  labels:
    app: zen-asr-server
spec:
  type: ClusterIP
  selector:
    app: zen-asr-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
